# Generated by Django 5.1.1 on 2024-10-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Kategori adı"
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Alt başlık"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/images",
                        verbose_name="Kategori resmi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_author",
                        to="members.member",
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_replies",
                        to="threads.comments",
                        verbose_name="Üst Yorum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yorum",
                "verbose_name_plural": "Yorumlar",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Beğenme tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.comments",
                        verbose_name="Yorum",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                        verbose_name="Üye",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beğeni",
                "verbose_name_plural": "Beğeniler",
                "db_table": "likes",
            },
        ),
        migrations.AddField(
            model_name="comments",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_likes",
                through="threads.Like",
                to="members.member",
                verbose_name="Beğeniler",
            ),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_author",
                        to="members.member",
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_set",
                        to="threads.comments",
                        verbose_name="Yorum",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reply_likes",
                        through="threads.Like",
                        to="members.member",
                        verbose_name="Beğeniler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yanıt",
                "verbose_name_plural": "Yanıtlar",
                "db_table": "replies",
            },
        ),
        migrations.AddField(
            model_name="like",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="threads.reply",
                verbose_name="Yanıt",
            ),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Başlık"
                    ),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Okunma sayısı"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                        verbose_name="Yazar",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="threads.category",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="thread_likes",
                        through="threads.Like",
                        to="members.member",
                        verbose_name="Beğeniler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konu",
                "verbose_name_plural": "Konular",
                "db_table": "threads",
            },
        ),
        migrations.AddField(
            model_name="like",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="threads.thread",
                verbose_name="Konu",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_comments",
                to="threads.thread",
                verbose_name="Konu",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="threads",
            field=models.ManyToManyField(
                blank=True,
                related_name="categories",
                to="threads.thread",
                verbose_name="Konular",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("member", "thread", "comment", "reply")},
        ),
    ]
