# Generated by Django 5.1.1 on 2024-09-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="replies",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="reply_likes",
                through="threads.Like",
                to="members.member",
                verbose_name="Beğeniler",
            ),
        ),
    ]
