# Generated by Django 5.1.1 on 2024-10-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="parent",
        ),
        migrations.AddField(
            model_name="comments",
            name="replies",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_replies",
                to="threads.reply",
                verbose_name="Yanıtlar",
            ),
        ),
        migrations.AddField(
            model_name="reply",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_parent",
                to="threads.reply",
                verbose_name="Üst Yanıt",
            ),
        ),
    ]
