# Generated by Django 5.1.1 on 2024-09-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_alter_memberrole_role"),
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AddField(
            model_name="thread",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="thread_likes",
                to="members.member",
                verbose_name="Beğeniler",
            ),
        ),
    ]
