# Generated by Django 5.1.1 on 2024-09-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0002_thread_is_active_thread_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="thread_comments",
                to="threads.comments",
                verbose_name="Yorumlar",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_threads",
                to="threads.thread",
                verbose_name="Konu",
            ),
        ),
    ]
