# Generated by Django 5.1.1 on 2024-10-02 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0002_remove_comments_parent_comments_replies_reply_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_set",
                to="threads.comments",
                verbose_name="Yorum",
            ),
        ),
    ]
