# Generated by Django 5.1.1 on 2024-09-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0002_replies_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Okunma sayısı"),
        ),
    ]
