# Generated by Django 5.1.1 on 2024-09-24 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0003_thread_comments_alter_comments_thread"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="comments",
        ),
    ]
