# Generated by Django 5.1.1 on 2024-10-02 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0003_alter_reply_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="threads.reply",
                verbose_name="Üst Yanıt",
            ),
        ),
    ]
