# Generated by Django 5.1.1 on 2024-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0004_remove_thread_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="thread_comments",
                to="threads.comments",
                verbose_name="Yorumlar",
            ),
        ),
    ]
