# Generated by Django 5.1.1 on 2024-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0005_thread_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="replies",
        ),
        migrations.AddField(
            model_name="comments",
            name="replies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="comment_replies",
                to="threads.replies",
                verbose_name="Cevaplar",
            ),
        ),
    ]
