# Generated by Django 5.1.1 on 2024-09-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_member_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberrole",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="members.member",
                verbose_name="Üye",
            ),
        ),
    ]
