# Generated by Django 5.1.1 on 2024-09-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_memberrole_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberrole",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberrole",
                to="members.member",
                verbose_name="Üye",
            ),
        ),
        migrations.AlterField(
            model_name="memberrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("member", "Üye"),
                ],
                max_length=100,
                verbose_name="Rol",
            ),
        ),
    ]
