# Generated by Django 5.1.1 on 2024-09-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_memberrole_member_alter_memberrole_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Son Geçerlilik Tarihi"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="members.member",
                        verbose_name="Üye",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye Tokeni",
                "verbose_name_plural": "Üye Tokenleri",
                "db_table": "member_tokens",
            },
        ),
    ]
