# Generated by Django 5.1.1 on 2024-09-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_member_country_of_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderatör"),
                    ("member", "Üye"),
                ],
                max_length=100,
                verbose_name="Rol",
            ),
        ),
    ]
