# Generated by Django 5.1.1 on 2024-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_alter_memberrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="terms",
            field=models.BooleanField(
                default=True, verbose_name="Forum kurallarını onayladı mı?"
            ),
        ),
    ]
